### ISSUE TITLE
Actions failing

### ISSUE THREAD

**Issue by Geokureli** [HaxeFlixel/haxeflixel.com#186]
this is preventing us from deploying, 

```
Error: Command failed: docker build -t haxeflixel.com .
    at checkExecSyncError (child_process.js:629:11)
    at execSync (child_process.js:666:13)
    at buildImage (/home/runner/work/haxeflixel.com/haxeflixel.com/scripts/docker.js:15:5)
    at Object.<anonymous> (/home/runner/work/haxeflixel.com/haxeflixel.com/scripts/docker.js:7:38)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
```

**Comment by Geokureli** [comment]
@RichardBray 
I need to [update one of the sponsors logos](https://github.com/HaxeFlixel/haxeflixel.com/commit/8035a119bfb2fb7abf70c682cc3316d8c9289329), but [github actions are failing](https://github.com/HaxeFlixel/haxeflixel.com/runs/7009136743?check_suite_focus=true) from what seems like docker issues, would you know how to fix those, or how to work around them?

**Comment by RichardBray** [comment]
Okay I think I might have something with this pull request

https://github.com/HaxeFlixel/haxeflixel.com/pull/187

Is there a way to get it to deploy to dev and not master?

**Comment by Geokureli** [comment]
Sorry I thought I replied to this already but I guess I haven't. 

It should deploy to dev because it is pointed at haxeFlixel:dev, check out [the github actions](https://github.com/HaxeFlixel/haxeflixel.com/blob/dev/.github/workflows/main.yml#L45).

**Comment by Geokureli** [comment]
just to be clear you're saying #187 is ready to be merged?

**Comment by Geokureli** [comment]
https://dev.haxeflixel.com/sponsors/
looking good, thanks! I'll see if I can cherry pick this change onto master. there's some flixel 5.0.0 things that aren't ready for master yet

**Comment by RichardBray** [comment]
Should this issue be closed? Unless there are still some issues with deployment 🤔
